site_name: releez
site_description: CLI tool for managing semantic versioned releases
site_url: https://hotdog-werx.github.io/releez
repo_url: https://github.com/hotdog-werx/releez
repo_name: hotdog-werx/releez

nav:
  - Home: index.md
  - Configuration:
      - Settings: configuration/settings.md
      - Hooks: configuration/hooks.md
  - GitHub Actions:
      - Action Reference: github-actions/action.md
      - Workflow Recipes: github-actions/workflow-recipes.md
  - Monorepo:
      - Setup Guide: monorepo/setup.md
      - Design Reference: monorepo/design.md

# Configuration
theme:
  name: material
  features:
    - announce.dismiss
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: lucide/sun
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: lucide/moon-star
        name: Switch to light mode
  # favicon: assets/zensical.png
  # logo: assets/zensical.svg
  icon:
    tag:
      default: lucide/hash

# Plugins
plugins:
  - search
  - tags

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hotdog-werx
