name: Lint PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: ./
        with:
          mode: validate-pr-title
          pr-title: ${{ github.event.pull_request.title }}
